global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'ash-rpc-server'
    static_configs:
      - targets: ['ash-rpc-server:3000']
    metrics_path: '/metrics'
    scrape_interval: 5s
